// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWXn2MgZQNAQp-IXVNjQv6cWrdSsevK2A',
    appId: '1:374459486225:web:7976b7497f1b1009a4e1b0',
    messagingSenderId: '374459486225',
    projectId: 'inatel-app-challenge',
    authDomain: 'inatel-app-challenge.firebaseapp.com',
    storageBucket: 'inatel-app-challenge.appspot.com',
    measurementId: 'G-2JP6WS212E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcrteVdTT7LbOGNuBNDUqWPNXacGwapPA',
    appId: '1:374459486225:android:cb6f75fcfd0d6288a4e1b0',
    messagingSenderId: '374459486225',
    projectId: 'inatel-app-challenge',
    storageBucket: 'inatel-app-challenge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmE8Lv7YJNT9-rXq5sVnfRs09xJuKO_sM',
    appId: '1:374459486225:ios:8949fa1ddbebd9bea4e1b0',
    messagingSenderId: '374459486225',
    projectId: 'inatel-app-challenge',
    storageBucket: 'inatel-app-challenge.appspot.com',
    iosClientId: '374459486225-3bdmk7ej4pccv7mkcvl5419ucm8ncnau.apps.googleusercontent.com',
    iosBundleId: 'com.example.inatelAppChallenge',
  );
}
